export const GET_GRADES = 'GET_GRADES';
export const ADD_GRADE = 'ADD_GRADE';
export const UPDATE_GRADE = 'UPDATE_GRADE';
export const DELETE_GRADE = 'DELETE_GRADE';
export const TOGGLE_GRADE_DIALOG = 'TOGGLE_GRADE_DIALOG';
export const SELECT_GRADE = 'SELECT_GRADE';
export const SELECT_ALL_GRADES = 'SELECT_ALL_GRADES';
