export const GET_LESSONS = 'GET_LESSONS';
export const ADD_LESSON = 'ADD_LESSON';
export const UPDATE_LESSON = 'UPDATE_LESSON';
export const DELETE_LESSON = 'DELETE_LESSON';
export const TOGGLE_LESSON_DIALOG = 'TOGGLE_LESSON_DIALOG';
export const SELECT_LESSON = 'SELECT_LESSON';
export const SELECT_ALL_LESSONS = 'SELECT_ALL_LESSONS';
